<?php

return [
    "tab_title" => "name",
    "module_name" => [
        "single" => "Klanten",
        "multiple" => "Klanten"
    ],
    "fields" => [
        "uploads" => [
            "active" => false,
            "type" => "",
            "title" => "Uploads",
            "read" => false,
            "required" => false,
            "edit" => false,
        ],
        "locale" => [
            "active" => false,
            "type" => "text",
            "title" => "Taal",
            "read" => true
        ],
        "name" => [
            "active" => true,
            "type" => "text",
            "title" => "Naam",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "email" => [
            "active" => true,
            "type" => "email",
            "title" => "E-mail",
            "read" => true,
            "required" => true,
            "edit" => true,
        ],
        "password" => [
            "active" => true,
            "type" => "password",
            "title" => "Wachtwoord",
            "read" => false,
            "required" => true,
            "edit" => true,
        ],
        "company_id" => [
            "active" => false,
            "type" => "number",
            "title" => "Bedrijf ID",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "host" => [
            "active" => false,
            "type" => "text",
            "title" => "Host",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "identifier" => [
            "active" => false,
            "type" => "text",
            "title" => "Identifier",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "relation_nr" => [
            "active" => false,
            "type" => "text",
            "title" => "Relatie Nr",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "debtor_nr" => [
            "active" => false,
            "type" => "text",
            "title" => "Debiteur Nr",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "user_nr" => [
            "active" => false,
            "type" => "text",
            "title" => "Gebruiker Nr",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "number" => [
            "active" => false,
            "type" => "text",
            "title" => "Nummer",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "sex" => [
            "active" => false,
            "type" => "text",
            "title" => "Geslacht",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "initials" => [
            "active" => false,
            "type" => "text",
            "title" => "Initialen",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "lastname" => [
            "active" => false,
            "type" => "text",
            "title" => "Achternaam",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "firstnames" => [
            "active" => false,
            "type" => "text",
            "title" => "Voorna(a)m(en)",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "nameInsertion" => [
            "active" => false,
            "type" => "text",
            "title" => "Tussenvoegsel",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "company" => [
            "active" => false,
            "type" => "text",
            "title" => "Bedrijf",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "companyNr" => [
            "active" => false,
            "type" => "text",
            "title" => "Bedrijfsnummer",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "taxNr" => [
            "active" => false,
            "type" => "text",
            "title" => "BTW Nummer",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "address" => [
            "active" => false,
            "type" => "text",
            "title" => "Adres",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "housenumber" => [
            "active" => false,
            "type" => "text",
            "title" => "Huisnummer",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "addressSuffix" => [
            "active" => false,
            "type" => "text",
            "title" => "Toevoeging Adres",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "zipcode" => [
            "active" => false,
            "type" => "text",
            "title" => "Postcode",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "city" => [
            "active" => false,
            "type" => "text",
            "title" => "Stad",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "country" => [
            "active" => false,
            "type" => "text",
            "title" => "Land",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "state" => [
            "active" => false,
            "type" => "text",
            "title" => "Staat/Provincie",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "birthdate" => [
            "active" => false,
            "type" => "date",
            "title" => "Geboortedatum",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "birthcity" => [
            "active" => false,
            "type" => "text",
            "title" => "Geboorteplaats",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "phone" => [
            "active" => false,
            "type" => "text",
            "title" => "Telefoon",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "phone2" => [
            "active" => false,
            "type" => "text",
            "title" => "Telefoon 2",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "bsn" => [
            "active" => false,
            "type" => "text",
            "title" => "BSN",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "iban" => [
            "active" => false,
            "type" => "text",
            "title" => "IBAN",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "maritalStatus" => [
            "active" => false,
            "type" => "text",
            "title" => "Burgerlijke Staat",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "lastLogin" => [
            "active" => false,
            "type" => "datetime",
            "title" => "Laatste Login",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "code" => [
            "active" => false,
            "type" => "text",
            "title" => "Code",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "admin" => [
            "active" => false,
            "type" => "boolean",
            "title" => "Admin",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "developer" => [
            "active" => false,
            "type" => "boolean",
            "title" => "Ontwikkelaar",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "comment" => [
            "active" => false,
            "type" => "textarea",
            "title" => "Opmerking",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "contactperson_id" => [
            "active" => false,
            "type" => "number",
            "title" => "Contactpersoon ID",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "administration" => [
            "active" => false,
            "type" => "text",
            "title" => "administration",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "identifier" => [
            "active" => false,
            "type" => "text",
            "title" => "identifier",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
    ]
];
