<select class="form-control form-control-sm @error('country')is-invalid @enderror" id="country" wire:model="country">
    <option value="">Kies een land</option>
    <option value="NL">Nederland</option>
    <option value="BE">Belgie</option>
    <option value="DE">Duitsland</option>
    <option value="FR">Frankrijk</option>
    <option value="ES">Spanje</option>
    <option value="GB">Verenigd Koningkrijk</option>
    <option disabled>&nbsp;</option>
    <option value="AF">Afghanistan</option>
    <option value="AX">Aland-eilanden</option>
    <option value="AL">Albanië</option>
    <option value="DZ">Algerije</option>
    <option value="AS">Amerikaans Samoa</option>
    <option value="AD">Andorra</option>
    <option value="AO">Angola</option>
    <option value="AI">Anguilla</option>
    <option value="AQ">Antarctica</option>
    <option value="AG">Antigua en Barbuda</option>
    <option value="AR">Argentinië</option>
    <option value="AM">Armenië</option>
    <option value="AW">Aruba</option>
    <option value="AU">Australië</option>
    <option value="AT">Oostenrijk</option>
    <option value="AZ">Azerbeidzjan</option>
    <option value="BS">Bahamas</option>
    <option value="BH">Bahrein</option>
    <option value="BD">Bangladesh</option>
    <option value="BB">Barbados</option>
    <option value="BY">Wit-Rusland</option>
    <option value="BZ">Belize</option>
    <option value="BJ">Benin</option>
    <option value="BM">Bermuda</option>
    <option value="BT">Bhutan</option>
    <option value="BO">Bolivia</option>
    <option value="BQ">Bonaire, Sint Eustatius en Saba</option>
    <option value="BA">Bosnië-Herzegovina</option>
    <option value="BW">Botswana</option>
    <option value="BV">Bouvet-eiland</option>
    <option value="BR">Brazilië</option>
    <option value="IO">Brits-Indisch oceaan gebied</option>
    <option value="BN">Brunei Darussalam</option>
    <option value="BG">Bulgarije</option>
    <option value="BF">Burkina Faso</option>
    <option value="BI">Burundi</option>
    <option value="KH">Cambodja</option>
    <option value="CM">Kameroen</option>
    <option value="CA">Canada</option>
    <option value="CV">Kaapverdië</option>
    <option value="KY">Kaaiman Eilanden</option>
    <option value="CF">Centraal Afrikaanse Republiek</option>
    <option value="TD">Tsjaad</option>
    <option value="CL">Chili</option>
    <option value="CN">China</option>
    <option value="CX">Kersteiland</option>
    <option value="CC">Cocos (Keeling) eilanden</option>
    <option value="CO">Colombia</option>
    <option value="KM">Comoren</option>
    <option value="CG">Congo</option>
    <option value="CD">Congo, Democratische Republiek Congo</option>
    <option value="CK">Cook Eilanden</option>
    <option value="CR">Costa Rica</option>
    <option value="CI">Ivoorkust</option>
    <option value="HR">Kroatië</option>
    <option value="CU">Cuba</option>
    <option value="CW">Curacao</option>
    <option value="CY">Cyprus</option>
    <option value="CZ">Tsjechië</option>
    <option value="DK">Denemarken</option>
    <option value="DJ">Djibouti</option>
    <option value="DM">Dominica</option>
    <option value="DO">Dominicaanse Republiek</option>
    <option value="EC">Ecuador</option>
    <option value="EG">Egypte</option>
    <option value="SV">El Salvador</option>
    <option value="GQ">Equatoriaal-Guinea</option>
    <option value="ER">Eritrea</option>
    <option value="EE">Estland</option>
    <option value="ET">Ethiopië</option>
    <option value="FK">Falklandeilanden (Malvinas)</option>
    <option value="FO">Faeröer</option>
    <option value="FJ">Fiji</option>
    <option value="FI">Finland</option>
    <option value="GF">Frans Guyana</option>
    <option value="PF">Frans-Polynesië</option>
    <option value="TF">Franse zuidelijke gebieden</option>
    <option value="GA">Gabon</option>
    <option value="GM">Gambia</option>
    <option value="GE">Georgië</option>
    <option value="GH">Ghana</option>
    <option value="GI">Gibraltar</option>
    <option value="GR">Griekenland</option>
    <option value="GL">Groenland</option>
    <option value="GD">Grenada</option>
    <option value="GP">Guadeloupe</option>
    <option value="GU">Guam</option>
    <option value="GT">Guatemala</option>
    <option value="GG">Guernsey</option>
    <option value="GN">Guinea</option>
    <option value="GW">Guinee-Bissau</option>
    <option value="GY">Guyana</option>
    <option value="HT">Haïti</option>
    <option value="HM">Heard Island en Mcdonald Islands</option>
    <option value="VA">Heilige Stoel (Vaticaanstad)</option>
    <option value="HN">Honduras</option>
    <option value="HK">Hong Kong</option>
    <option value="HU">Hongarije</option>
    <option value="IS">IJsland</option>
    <option value="IN">India</option>
    <option value="ID">Indonesië</option>
    <option value="IR">Iran, Islamitische Republiek</option>
    <option value="IQ">Irak</option>
    <option value="IE">Ierland</option>
    <option value="IM">Isle of Man</option>
    <option value="IL">Israël</option>
    <option value="IT">Italië</option>
    <option value="JM">Jamaica</option>
    <option value="JP">Japan</option>
    <option value="JE">Jersey</option>
    <option value="JO">Jordanië</option>
    <option value="KZ">Kazachstan</option>
    <option value="KE">Kenia</option>
    <option value="KI">Kiribati</option>
    <option value="KP">Korea, Democratische Volksrepubliek</option>
    <option value="KR">Korea, republiek van</option>
    <option value="XK">Kosovo</option>
    <option value="KW">Koeweit</option>
    <option value="KG">Kirgizië</option>
    <option value="LA">Lao Democratische Volksrepubliek</option>
    <option value="LV">Letland</option>
    <option value="LB">Libanon</option>
    <option value="LS">Lesotho</option>
    <option value="LR">Liberia</option>
    <option value="LY">Libië</option>
    <option value="LI">Liechtenstein</option>
    <option value="LT">Litouwen</option>
    <option value="LU">Luxemburg</option>
    <option value="MO">Macao</option>
    <option value="MK">Macedonië, de voormalige Joegoslavische Republiek</option>
    <option value="MG">Madagascar</option>
    <option value="MW">Malawi</option>
    <option value="MY">Maleisië</option>
    <option value="MV">Maldiven</option>
    <option value="ML">Mali</option>
    <option value="MT">Malta</option>
    <option value="MH">Marshall eilanden</option>
    <option value="MQ">Martinique</option>
    <option value="MR">Mauritanië</option>
    <option value="MU">Mauritius</option>
    <option value="YT">Mayotte</option>
    <option value="MX">Mexico</option>
    <option value="FM">Micronesië, Federale Staten van</option>
    <option value="MD">Moldavië, Republiek</option>
    <option value="MC">Monaco</option>
    <option value="MN">Mongolië</option>
    <option value="ME">Montenegro</option>
    <option value="MS">Montserrat</option>
    <option value="MA">Marokko</option>
    <option value="MZ">Mozambique</option>
    <option value="MM">Myanmar</option>
    <option value="NA">Namibië</option>
    <option value="NR">Nauru</option>
    <option value="NP">Nepal</option>
    <option value="AN">Nederlandse Antillen</option>
    <option value="NC">Nieuw-Caledonië</option>
    <option value="NZ">Nieuw-Zeeland</option>
    <option value="NI">Nicaragua</option>
    <option value="NE">Niger</option>
    <option value="NG">Nigeria</option>
    <option value="NU">Niue</option>
    <option value="NF">Norfolkeiland</option>
    <option value="MP">noordelijke Mariana eilanden</option>
    <option value="NO">Noorwegen</option>
    <option value="OM">Oman</option>
    <option value="PK">Pakistan</option>
    <option value="PW">Palau</option>
    <option value="PS">Palestijns gebied, bezet</option>
    <option value="PA">Panama</option>
    <option value="PG">Papoea-Nieuw-Guinea</option>
    <option value="PY">Paraguay</option>
    <option value="PE">Peru</option>
    <option value="PH">Filippijnen</option>
    <option value="PN">Pitcairn</option>
    <option value="PL">Polen</option>
    <option value="PT">Portugal</option>
    <option value="PR">Puerto Rico</option>
    <option value="QA">Qatar</option>
    <option value="RE">Bijeenkomst</option>
    <option value="RO">Roemenië</option>
    <option value="RU">Russische Federatie</option>
    <option value="RW">Rwanda</option>
    <option value="BL">Sint-Bartholomeus</option>
    <option value="SH">Sint-Helena</option>
    <option value="KN">Saint Kitts en Nevis</option>
    <option value="LC">Saint Lucia</option>
    <option value="MF">Sint-Maarten</option>
    <option value="PM">Saint Pierre en Miquelon</option>
    <option value="VC">Saint Vincent en de Grenadines</option>
    <option value="WS">Samoa</option>
    <option value="SM">San Marino</option>
    <option value="ST">Sao Tomé en Principe</option>
    <option value="SA">Saoedi-Arabië</option>
    <option value="SN">Senegal</option>
    <option value="RS">Servië</option>
    <option value="CS">Servië en Montenegro</option>
    <option value="SC">Seychellen</option>
    <option value="SL">Sierra Leone</option>
    <option value="SG">Singapore</option>
    <option value="SX">Sint Maarten</option>
    <option value="SK">Slowakije</option>
    <option value="SI">Slovenië</option>
    <option value="SB">Solomon eilanden</option>
    <option value="SO">Somalië</option>
    <option value="ZA">Zuid-Afrika</option>
    <option value="GS">Zuid-Georgië en de Zuidelijke Sandwicheilanden</option>
    <option value="SS">Zuid Soedan</option>
    <option value="LK">Sri Lanka</option>
    <option value="SD">Soedan</option>
    <option value="SR">Suriname</option>
    <option value="SJ">Svalbard en Jan Mayen</option>
    <option value="SZ">Swaziland</option>
    <option value="SE">Zweden</option>
    <option value="CH">Zwitserland</option>
    <option value="SY">Syrische Arabische Republiek</option>
    <option value="TW">Taiwan, provincie China</option>
    <option value="TJ">Tadzjikistan</option>
    <option value="TZ">Tanzania, Verenigde Republiek</option>
    <option value="TH">Thailand</option>
    <option value="TL">Oost-Timor</option>
    <option value="TG">Gaan</option>
    <option value="TK">Tokelau</option>
    <option value="TO">Tonga</option>
    <option value="TT">Trinidad en Tobago</option>
    <option value="TN">Tunesië</option>
    <option value="TR">kalkoen</option>
    <option value="TM">Turkmenistan</option>
    <option value="TC">Turks- en Caicoseilanden</option>
    <option value="TV">Tuvalu</option>
    <option value="UG">Oeganda</option>
    <option value="UA">Oekraïne</option>
    <option value="AE">Verenigde Arabische Emiraten</option>
    <option value="US">Verenigde Staten</option>
    <option value="UM">Kleine afgelegen eilanden van de Verenigde Staten</option>
    <option value="UY">Uruguay</option>
    <option value="UZ">Oezbekistan</option>
    <option value="VU">Vanuatu</option>
    <option value="VE">Venezuela</option>
    <option value="VN">Vietnam</option>
    <option value="VG">Britse Maagdeneilanden</option>
    <option value="VI">Maagdeneilanden, U.s.</option>
    <option value="WF">Wallis en Futuna</option>
    <option value="EH">Westelijke Sahara</option>
    <option value="YE">Jemen</option>
    <option value="ZM">Zambia</option>
    <option value="ZW">Zimbabwe</option>
</select>
